### PR TITLE
Various improvements on input.

### PR DESCRIPTION
**Pull request by AurelienFT**
This PR implements various improvements for the input :

- [x] Ability go to others lines with arrows when having a multiple lines input
- [x] Deleting in an other line
- [x] Adding shortcuts for fast forward left/right
- [x] Fix history rewriting only one line when we are in a multiple lines input

Future : 

- [ ] Adding more shortcuts like #230

### CODE REVIEW

**Comment by AurelienFT** [comment]
Converting to draft to add ALT + Arrow to fast forward a word left/right.

**Comment by AurelienFT** [comment]
Ready for review. Do not hesitate to ask any questions :) (cc @pksunkara)

**Comment by pksunkara** [comment]
> Ability go to others lines with arrows when having a multiple lines input

Does this happen because of small terminal size?

**Comment by AurelienFT** [comment]
> > Ability go to others lines with arrows when having a multiple lines input
> 
> Does this happen because of small terminal size?

It can be a reason but also when we have a big input and we want to modify it we couldn't, with this PR you can and you can also fast forward.

**Review by pksunkara — APPROVED** [review]

**Comment by AurelienFT** [comment]
@pksunkara can you release a version with this PR?

**Comment by samuela** [comment]
I'm currently on 3d0ba2dd74dac10d0894dd4a976f43c9ca545bab which postdates this PR, and alt+{left, right, backspace} are still not working :( I'm running `cargo run --example input` on macOS 14.1.1 with iTerm 3.4.23. 

Any ideas what might be going wrong?

**Pull request merged**
