### PR TITLE
Adding post completion text for input

### PR DESCRIPTION
**Pull request by robinbernon**
Adding option to be able to change the prompt text after an input has been given.

### CODE REVIEW

**Review by pksunkara — COMMENTED** [review]
Like the idea but I think the name needs to be better. Any other ideas?

**Comment by robinbernon** [comment]
> Like the idea but I think the name needs to be better. Any other ideas?

Only thing that could be more clear here is something like - "with_post_completion_prompt_change". Would you be happy to merge the PR if I change the method to this instead?

**Review by pksunkara — COMMENTED** [review]
Hmm.. would your use case be solved by turning off report and then using `TermThemeRenderer` yourself?

**Comment by robinbernon** [comment]
> Hmm.. would your use case be solved by turning off report and then using `TermThemeRenderer` yourself?

How would that be possible? Also if it maybe was the case (which I can't see), wouldn't it be best to offer this as a first class feature as it is pretty useful?

**Review by pksunkara — APPROVED** [review]

**Pull request merged**
