### PR TITLE
Zeroize a password confirmation buffer securely

### PR DESCRIPTION
**Pull request by fadeevab**
I used `secrecy` crate to automatically zeroize an internal confirmation string on drop. Another option is to use `zeroize` crate directly, but in that case need to call `pw2.zeroize()` twice in two if-else cases.

Solves #49.

### CODE REVIEW

**Comment by fadeevab** [comment]
Tell me if additional documentation should be commited

**Comment by pksunkara** [comment]
Looks okay, but I am worried about the MSRV bump to 1.39

**Comment by fadeevab** [comment]
Oh, I see... I quickly checked, it doesn't seem like both crates really use rust features of 1.39+, I see they modified README (1.36->1.39) and added a few commits after that with nothing specific. Either way what is the minimum rust version of `dialoguer`?

**Comment by pksunkara** [comment]
I am not sure what dialoguer's MSRV is.

**Comment by fadeevab** [comment]
Nice:) Does it mean we stuck? :)

**Comment by pksunkara** [comment]
Maybe for a few more rust versions?

**Comment by fadeevab** [comment]
@pksunkara Ok, what I think, dialoguer's minimum rust version might be 1.31, 2018 edition, right? So let me check whether `secrecy` is compatible with this version. And as an option I will find a bit older but compatible version of secrecy. Thank you for your patience

**Comment by fadeevab** [comment]
Closed in favor of PR #55

**Pull request closed without merging**
